# -*- coding: utf-8 -*-
"""FireFighter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyoRWBlyYnEKlapI8oj7ejYHaoYc9Y0Q
"""

# Commented out IPython magic to ensure Python compatibility.
# Importamos las clases que se requieren para manejar los agentes (Agent) y su entorno (Model).
# Cada modelo puede contener múltiples agentes.
from mesa import Agent, Model

# Debido a que necesitamos que existe un solo agente por celda, elegimos ''SingleGrid''.
from mesa.space import SingleGrid, MultiGrid

# Con ''RandomActivation'', hacemos que todos los agentes se activen ''al mismo tiempo''.
from mesa.time import RandomActivation

# Haremos uso de ''batch_run'' para ejecutar varias simulaciones
from mesa.batchrunner import batch_run

# seaborn lo usaremos desplegar una gráficas más ''vistosas'' de
# nuestro modelo
import seaborn as sns

from functools import partial

# Haremos uso de ''DataCollector'' para obtener información de cada paso de la simulación.
from mesa.datacollection import DataCollector

# matplotlib lo usaremos crear una animación de cada uno de los pasos del modelo.
# %matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.animation as animation
plt.rcParams["animation.html"] = "jshtml"
matplotlib.rcParams['animation.embed_limit'] = 2**128

# Importamos los siguientes paquetes para el mejor manejo de valores numéricos.
import numpy as np
import pandas as pd

# Definimos otros paquetes que vamos a usar para medir el tiempo de ejecución de nuestro algoritmo.
import time
import datetime
import random

import heapq
from typing import List, Tuple, Dict

import json

# Firefighter
class FireFighter(Agent):
    def __init__(self, id, model, x, y):
        super().__init__(id, model)
        self.energy = 4
        self.carrying = False
        self.path = []
        self.movesToGoal = []
        self.previousPos = self.pos
        self.nextPos = None
        self.nearestPOI = None
        self.nearestEntrypoint = None
        self.isBlocked = False
        self.canAdvance = True
        self.moveCost = 1
        self.move_index = 1
        self.initialPos = (x, y)


    def calculatenearest(self):

      # Calcula el poi mas cercano a su tile actual
      current_tile = [obj for obj in self.model.grid.get_cell_list_contents([self.pos]) if isinstance(obj, Tile)][0]
      if self.carrying == False and len(self.model.POIsPositions) > 0:
        distances = {poi: abs(poi[0] - current_tile.pos[0]) + abs(poi[1]-current_tile.pos[1]) for poi in self.model.POIsPositions}
        # print("Nearest Poi:", min(distances, key=distances.get))
        self.nearestPOI = min(distances, key=distances.get)
      elif self.carrying == True:
        distances = {entrypoint: abs(entrypoint[0] - current_tile.pos[0]) + abs(entrypoint[1]-current_tile.pos[1]) for entrypoint in self.model.entryPoints}
        # print("Nearest Entrypoint:", min(distances, key=distances.get))
        self.nearestEntrypoint = min(distances, key=distances.get)


    def dijkstra_to_nearest(self, graph: Dict[Tuple[int, int], Dict[Tuple[int, int], int]],
                            start: Tuple[int, int],
                            poi: Tuple[int, int]) -> Tuple[List[Tuple[int, int]], int,]:

        self.movesToGoal = []

        path = []
        distances = {node: float('infinity') for node in graph}
        distances[start] = 0
        pq = [(0, start)]
        previous = {}

        while pq:
            current_distance, current_node = heapq.heappop(pq)

            if current_node == poi:
                while current_node in previous:
                    path.append(current_node)
                    current_node = previous[current_node]
                path.append(start)
                path = list(reversed(path))
                print(f"Distance {current_distance}")
                break

            if current_distance > distances[current_node]:
                continue

            for neighbor, weight in graph[current_node].items():
                distance = current_distance + weight
                if distance < distances[neighbor]:
                    distances[neighbor] = distance
                    previous[neighbor] = current_node
                    heapq.heappush(pq, (distance, neighbor))

        self.movesToGoal = path
        if self.carrying == False:
            print(f"Shortest path from {self.pos} to POI {self.nearestPOI}:")
        else:
            print(f"Shortest path from {self.pos} to entry point {self.nearestEntrypoint}:")
        print(" -> ".join(str(node) for node in self.movesToGoal))




  # Se mueve por los espacios que marca cada Tile, evitando paredes
    def move(self, next_position):

        # Posicion actual del agente
        current_position = self.pos
        print(f"Firefighter {self.unique_id} is at position {current_position}")

        # Obtener el Tile actual
        current_tile = [obj for obj in self.model.grid.get_cell_list_contents([current_position]) if isinstance(obj, Tile)][0]

        current_tile.hasFireFighter.remove(self)


        next_tile = [obj for obj in self.model.grid.get_cell_list_contents([next_position]) if isinstance(obj, Tile)][0]
        next_tile.hasFireFighter.append(self)

        print(f"Firefighter {self.unique_id} moved from {self.pos} to {next_position}")
        self.model.grid.move_agent(self, next_position)


        dx = next_position[0] - current_position[0]
        dy = next_position[1] - current_position[1]
        self.model.appendAffectedTile(current_tile, "move", dx, dy)

        if self.carrying:
            self.energy -= 2
        else:
            self.energy -= 1

        # Si en la posicion nueva se encuentra un POI, lo revela
        if next_tile.hasPOI == True:
            print("POI revelado!")
            next_tile.hasPOI = False
            self.model.numOfPOIs -=1
            if next_tile.poi == "v":
                print("Victima en POI")
                next_tile.numberOfVictims += 1
                self.carryVictim()
            else:
                print("Falsa alarma")
            next_tile.poi = None
            self.model.currentPOIS -= 1

        self.model.appendAffectedTile(next_tile, "stand", dx, dy)
        print(f"Affected tiles:")
        for tilelist in self.model.affectedTiles:
            print(tilelist)
        self.model.affectedTiles = []

        # Obtener todos los agentes en la nueva posición
        cell_contents = self.model.grid.get_cell_list_contents([next_position])
        for obj in cell_contents:
            if isinstance(obj, Tile):
                # print(f"Tile en nueva posición: {next_position}, con propiedades: Top={obj.wall.top}, Bottom={obj.wall.bottom}, Left={obj.wall.left}, Right={obj.wall.right}")
                pass


    def step(self):
        print(f"AGENT: {self.unique_id}")

        self.move_index = 1
        self.model.replenishPOIs()
        print(f"Carreando {self.carrying}")

        if self.carrying == False:
            self.calculatenearest()
            self.dijkstra_to_nearest(self.model.graph, self.pos, self.nearestPOI)
            goalPos = self.nearestPOI
        else:
            self.calculatenearest()
            self.dijkstra_to_nearest(self.model.graph, self.pos, self.nearestEntrypoint)
            goalPos = self.nearestEntrypoint



        print(f"Move index: {self.move_index}")
        if self.move_index < len(self.movesToGoal):
            print(f"Siguiente posicion: {self.movesToGoal[self.move_index]}")

        print(f"Energy: {self.energy}")
        print(f"Len(moves to poi): {len(self.movesToGoal)}")
        while self.energy > 0 and self.move_index < len(self.movesToGoal) and self.canAdvance == True:

            move = self.movesToGoal[self.move_index]
            # itera en la lista de movesToGoal empezando por el segundo elemento

            current_tile = [obj for obj in self.model.grid.get_cell_list_contents([self.pos]) if isinstance(obj, Tile)][0]
            next_tile = [obj for obj in self.model.grid.get_cell_list_contents([move]) if isinstance(obj, Tile)][0]
            # Evalua si existe algun tipo de bloqueo entre la posicion actual
            print(f"Posicion actual: {self.pos}")
            print(f"Siguiente posicion: {move}")


            match self.model.graph[self.pos][move]:
                case 1:
                    self.isBlocked = False
                case 2:
                    self.isBlocked = True
                    blocker = "Door"
                    print("Blocked by door")
                case 3:
                    self.isBlocked = True
                    blocker = "Damaged Wall"
                    print("Blocked by Damaged Wall")
                case 5:
                    self.isBlocked = True
                    blocker = "Wall"
                    print("Blocked by Wall")

            if self.isBlocked == False and self.canAdvance:
                if next_tile.fireStatus == 2:
                    print("Fire detected")
                    if self.energy >= 2:
                        print("Fire extinguished")
                        self.extinguish(move)

                    else:
                        print("Fire couldnt be extinguished in the current turn")
                        self.canAdvance = False
                else:
                    if self.energy>= self.moveCost:
                        # print("Moving")
                        self.move(move)
                        self.move_index += 1
                    else:
                        print("Couldnt move in the current turn")
                        self.canAdvance = False
            elif self.isBlocked == True and self.canAdvance:
                match blocker:
                    case "Door":
                        if self.energy >= 1:
                            print("Door opened")
                            self.manipulateDoor(True, move)
                            self.model.graph[self.pos][move] = 1
                            self.model.graph[move][self.pos] = 1
                        else:
                            print("Door couldnt be opened in the current turn")
                            self.canAdvance = False
                    case "Damaged Wall":
                        if self.energy >= 2:
                            print("Damaged wall destroyed")
                            self.damage(False, move)
                            self.model.graph[self.pos][move] = 1
                            self.model.graph[move][self.pos] = 1
                        else:
                            print("Damaged wall couldnt be destroyed in the current turn")
                            self.canAdvance = False
                    case "Wall":
                        if self.energy >= 4:
                            print("Wall destroyed")
                            self.damage(True, move)
                            self.model.graph[self.pos][move] = 1
                            self.model.graph[move][self.pos] = 1
                        else:
                            print("Wall couldnt be destroyed in the current turn")
                            self.canAdvance = False

            print("Energy: ", self.energy)

        if self.pos == self.nearestPOI:
            self.move_index = 1
            print("Posicion del POI alcanzada")

        if self.pos == self.nearestEntrypoint:
            self.move_index = 1
            print("Posicion del punto de entrada alcanzada")
            self.dropVictim()

        if self.energy <= 0:
            print("Energia terminada")
            self.move_index = 1

        # Reiniciar el nivel de energia para el siguiente turno
        self.energy = 4 + self.energy
        if self.energy > 8:
            self.energy = 8

        self.canAdvance = True
        self.model.throwDice()
        print(f"All tiles per turn:")
        for cuadrante in self.model.allTiles:
            print(cuadrante)

        print("===========================Damage counter", self.model.damageCounter)

        self.model.currentAgentsDictionary[self.unique_id] = self.model.allTiles
        print(f"Current agents dictionary:")
        for key in self.model.currentAgentsDictionary:
            print(f"{key}: {self.model.currentAgentsDictionary[key]}")

        self.model.allTiles = []






    def manipulateDoor(self, status, next_pos): # True para cerrar puerta, false para abrirla
        current_tile = [obj for obj in self.model.grid.get_cell_list_contents([self.pos]) if isinstance(obj, Tile)][0]
        tile2 = [obj for obj in self.model.grid.get_cell_list_contents([next_pos]) if isinstance(obj, Tile)][0]
        current_tile.wall.isOpen = status
        tile2.wall.isOpen = status
        dx = next_pos[0] - self.pos[0]
        dy = next_pos[1] - self.pos[1]

        self.energy -= 1
        self.model.appendAffectedTile(current_tile,"stand", dx, dy)
        self.model.appendAffectedTile(tile2,"stand", dx, dy)
        print(f"Affected tiles:")
        for tilelist in self.model.affectedTiles:
            print(tilelist)
        self.model.affectedTiles = []


    def extinguish(self, move):
        current_tile = [obj for obj in self.model.grid.get_cell_list_contents([self.pos]) if isinstance(obj, Tile)][0]
        next_tile = [obj for obj in self.model.grid.get_cell_list_contents([move]) if isinstance(obj, Tile)][0]
        next_tile.fireStatus = 0
        self.energy -= 2

        dx = move[0] - self.pos[0]
        dy = move[1] - self.pos[1]
        self.model.appendAffectedTile(next_tile,"stand", dx, dy)

    def damage(self, demolish, next_pos):
        current_tile = [obj for obj in self.model.grid.get_cell_list_contents([self.pos]) if isinstance(obj, Tile)][0]

        dx = next_pos[0] - self.pos[0]
        dy = next_pos[1] - self.pos[1]
        other_tile = [obj for obj in self.model.grid.get_cell_list_contents([(self.pos[0]+dx, self.pos[1]+dy)]) if isinstance(obj, Tile)][0]

        if demolish:
            self.energy -= 4
            self.model.damageCounter += 2

            if dx == -1:
                other_tile.wall.bottomHealth = 0
                other_tile.wall.bottom = 0
                current_tile.wall.topHealth = 0
                current_tile.wall.top = 0
            elif dy == -1:
                other_tile.wall.rightHealth = 0
                other_tile.wall.right = 0
                current_tile.wall.leftHealth = 0
                current_tile.wall.left = 0
            elif dx == 1:
                other_tile.wall.topHealth = 0
                other_tile.wall.top = 0
                current_tile.wall.bottomHealth = 0
                current_tile.wall.bottom = 0
            elif dy == 1:
                other_tile.wall.leftHealth = 0
                other_tile.wall.left = 0
                current_tile.wall.rightHealth = 0
                current_tile.wall.right = 0
        else:
            self.energy -= 2
            self.model.damageCounter += 1
            if dx == -1:
                other_tile.wall.bottomHealth -= 2
                if other_tile.wall.bottomHealth <= 0:
                    other_tile.wall.bottom = 0
                current_tile.wall.topHealth -= 2
                if current_tile.wall.topHealth <= 0:
                    current_tile.wall.top = 0
            elif dy == -1:
                other_tile.wall.rightHealth -= 2
                if other_tile.wall.rightHealth <= 0:
                    other_tile.wall.right = 0
                current_tile.wall.leftHealth -= 2
                if current_tile.wall.leftHealth <= 0:
                    current_tile.wall.left = 0
            elif dx == 1:
                other_tile.wall.topHealth -= 2
                if other_tile.wall.topHealth <= 0:
                    other_tile.wall.top = 0
                current_tile.wall.bottomHealth -= 2
                if current_tile.wall.bottomHealth <= 0:
                    current_tile.wall.bottom = 0
            elif dy == 1:
                other_tile.wall.leftHealth -= 2
                if other_tile.wall.leftHealth <= 0:
                    other_tile.wall.left = 0
                current_tile.wall.rightHealth -= 2
                if current_tile.wall.rightHealth <= 0:
                    current_tile.wall.right = 0

        self.model.appendAffectedTile(current_tile,"stand", dx, dy)
        self.model.appendAffectedTile(other_tile,"stand", dx, dy)
        print(f"Affected tiles:")
        for tilelist in self.model.affectedTiles:
            print(tilelist)
        self.model.affectedTiles = []

    def carryVictim(self):
        current_tile = [obj for obj in self.model.grid.get_cell_list_contents([self.pos]) if isinstance(obj, Tile)][0]
        if current_tile.numberOfVictims > 0:
            print("Carreando")
            self.carrying = True
            current_tile.numberOfVictims -= 1
            self.moveCost = 2


    def dropVictim(self):
        current_tile = [obj for obj in self.model.grid.get_cell_list_contents([self.pos]) if isinstance(obj, Tile)][0]
        self.carrying = False
        self.moveCost = 1
        self.model.savedVictims += 1
        print("Victim saved")
        self.model.appendAffectedTile(current_tile,"stand", 0, 0)

class Wall():
    def __init__(self, id, top, left, bottom, right, isDoor=0, isOpen=False):
        self.unique_id = id
        self.top = top
        self.bottom = bottom
        self.left = left
        self.right = right
        self.isDoor = isDoor
        self.isOpen = isOpen
        self.topHealth = 4 * top
        self.bottomHealth = 4 * bottom
        self.leftHealth = 4 * left
        self.rightHealth = 4 * right

        if self.isDoor != 0:
            if self.isDoor == 1:
                self.top = 2
                self.topHealth = 2
            if self.isDoor == 2:
                self.left = 2
                self.leftHealth = 2
            if self.isDoor == 3:
                self.bottom = 2
                self.bottomHealth = 2
            if self.isDoor == 4:
                self.right = 2
                self.rightHealth = 2

class Tile():
  def __init__(self, id, top, left, bottom, right, isDoor, isOpen=False):
    self.unique_id = id
    self.pos = None
    self.wall = Wall(id, top, left, bottom, right, isDoor, isOpen)
    self.fireStatus = 0
    self.hasPOI = False
    self.numberOfVictims = 0
    self.hasFireFighter = []
    self.poi = None

def get_grid(model):
  grid = np.zeros((model.grid.width, model.grid.height))
  for content, (x, y) in model.grid.coord_iter():
    if content:
      grid[x][y] = 1
  return grid

def match_elements(model):
    grid = np.zeros((model.grid.width, model.grid.height))

    for agent in model.schedule.agents:
        grid[agent.pos[0], agent.pos[1]] = 1

    return grid

class FireRescueModel(Model):
    def __init__(self, firefighters, width, height, entrypoints, walls, doors, fires, pois):
        super().__init__()
        self.grid = MultiGrid(width, height, torus=False)
        self.schedule = RandomActivation(self)
        self.datacollector = DataCollector(model_reporters={"Grid": get_grid,
                                                            "Match": match_elements,
                                                            "Steps": lambda model: model.steps})
        self.steps = 0
        self.entryPoints = entrypoints
        self.damageCounter = 0
        self.numOfPOIs = 15
        self.truePOIs = 10
        self.falsePOIs = 5
        self.currentPOIS = 0
        self.savedVictims = 0
        self.deadVictims = 0
        self.running = True
        self.POIsPositions = []
        self.dictionaryList = []
        self.tilesMatrix = {}
        self.initialDictionary = {}
        self.currentAgentsDictionary = {}
        self.walls = walls
        self.doors = doors
        self.win = 0
        self.lose = 0
        self.affectedTiles = []
        self.allTiles = []
        self.graph = self.generate_graph(walls)
        self.graph = self.add_door_arches(self.graph, doors, cost=2)

        # Colocar los cuadrantes
        for j, row in enumerate(walls):
            for i, wall in enumerate(row):
                entryPointTile = False
                for point in entrypoints:
                    if point[0] == j+1 and point[1] == i+1: # Verifica si el cuadrante colocado tiene un punto de entrada
                        if point[0] == 1: # Punto de entrada superior
                            tile = Tile((j+1,i+1), wall[0], wall[1], wall[2], wall[3], 1, True)
                            entryPointTile = True
                        elif point[1] == 1: # Punto de entrada izquierda
                            tile = Tile((j+1,i+1), wall[0], wall[1], wall[2], wall[3], 2, True)
                            entryPointTile = True
                        elif point[0] == 6: # Punto de entrada inferior
                            tile = Tile((j+1,i+1), wall[0], wall[1], wall[2], wall[3], 3, True)
                            entryPointTile = True
                        elif point[1] == 8: # Punto de entrada derecha
                            tile = Tile((j+1,i+1), wall[0], wall[1], wall[2], wall[3], 4, True)
                            entryPointTile = True

                if not entryPointTile:
                    tile = Tile((j+1,i+1), wall[0], wall[1], wall[2], wall[3], 0)

                self.grid.place_agent(tile, (j+1, i+1))


        # Colocar fuegos
        for fire in fires:
            tile = [obj for obj in self.grid.get_cell_list_contents([(fire[0], fire[1])]) if isinstance(obj, Tile)][0]
            tile.fireStatus = 2

        # Colocar puertas
        for door in doors:
            x1, y1, x2, y2 = door

            tile1 = [obj for obj in self.grid.get_cell_list_contents([(x1, y1)]) if isinstance(obj, Tile)][0]
            tile2 = [obj for obj in self.grid.get_cell_list_contents([(x2, y2)]) if isinstance(obj, Tile)][0]

            dx = abs(x1 - x2)
            dy = abs(y1 - y2)

            if dx == 0 and dy == 1:
                # Los tiles están uno al lado del otro horizontalmente
                if y1 < y2:
                    tile1.wall.right = 2
                    tile2.wall.left = 2
                    tile1.wall.isDoor = 4
                    tile2.wall.isDoor = 2
                    tile1.wall.rightHealth = 2
                    tile2.wall.leftHealth = 2
                else:
                    tile1.wall.left = 2
                    tile2.wall.right = 2
                    tile1.wall.isDoor = 2
                    tile2.wall.isDoor = 4
                    tile1.wall.leftHealth = 2
                    tile2.wall.rightHealth = 2

            elif dy == 0 and dx == 1:
                # Los tiles están uno encima del otro verticalmente
                if x1 < x2:
                    tile1.wall.bottom = 2
                    tile2.wall.top = 2
                    tile1.wall.isDoor = 3
                    tile2.wall.isDoor = 1
                    tile1.wall.bottomHealth = 2
                    tile2.wall.topHealth = 2
                else:
                    tile1.wall.top = 2
                    tile2.wall.bottom = 2
                    tile1.wall.isDoor = 1
                    tile2.wall.isDoor = 3
                    tile1.wall.topHealth = 2
                    tile2.wall.bottomHealth = 2


        # Colocar bomberos fuera de la casa en los puntos de entrada
        for i in range(firefighters):
            x, y = random.choice(entryPoints)
            tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]
            print(f"Position of firefighter {i} in {x, y}")
            firefighter = FireFighter(i, self, x, y)
            tile.hasFireFighter.append(firefighter)
            self.grid.place_agent(firefighter, (x, y))
            self.schedule.add(firefighter)


        # Colocar POIS (Puntos de interes)
        for poi in pois:
            print(f"Spawning pois")
            x, y, victim = poi
            tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]
            self.spawnPOI(x, y, tile, victim)
            self.affectedTiles = []

        for i in range(1, self.grid.width-1):
            for j in range(1, self.grid.height-1):
                tile = [obj for obj in self.grid.get_cell_list_contents([(i, j)]) if isinstance(obj, Tile)][0]
                self.tilesMatrix[(i, j)] = [tile.wall.top, tile.wall.left, tile.wall.bottom, tile.wall.right]


    def appendAffectedTile(self, tile, stateString, dx, dy):
        firefightersIDs = []
        for firefighter in tile.hasFireFighter:
            firefightersIDs.append(firefighter.unique_id)

        self.affectedTiles.append([tile.pos,
                                   tile.wall.top,
                                   tile.wall.left,
                                   tile.wall.bottom,
                                   tile.wall.right,
                                   tile.wall.isOpen,
                                   tile.wall.topHealth,
                                   tile.wall.leftHealth,
                                   tile.wall.bottomHealth,
                                   tile.wall.rightHealth,
                                   tile.fireStatus,
                                   tile.hasPOI,
                                   tile.numberOfVictims,
                                   firefightersIDs,
                                   stateString,
                                   dx,
                                   dy,
                                   self.damageCounter,
                                   tile.poi,
                                   self.savedVictims,
                                   self.deadVictims])
        self.allTiles.append([tile.pos,
                                   tile.wall.top,
                                   tile.wall.left,
                                   tile.wall.bottom,
                                   tile.wall.right,
                                   tile.wall.isOpen,
                                   tile.wall.topHealth,
                                   tile.wall.leftHealth,
                                   tile.wall.bottomHealth,
                                   tile.wall.rightHealth,
                                   tile.fireStatus,
                                   tile.hasPOI,
                                   tile.numberOfVictims,
                                   firefightersIDs,
                                   stateString,
                                   dx,
                                   dy,
                                   self.damageCounter,
                                   tile.poi,
                                   self.savedVictims,
                                   self.deadVictims])



    def revealPOI(self, current_tile):
        # Si el tile con fuego tiene un POI, lo revela y mata a la victima en caso de tener
        if current_tile.hasPOI == True:
            print(f"POI burned at tile {current_tile.pos[0]}, {current_tile.pos[1]}")
            current_tile.hasPOI = False
            self.numOfPOIs -=1
            self.currentPOIS -= 1
            if current_tile.poi == "v":
                print("Dead victim")
                current_tile.numberOfVictims -= 1
                self.deadVictims += 1
                current_tile.poi = None
            else:
                print("False alarm")

    def spawnPOI(self, x, y, tile, victim):
        # Si el POI cae en un agente...
        # se revela y se disminuye el numero de pois
        while len(tile.hasFireFighter) > 0:
            tile.hasPOI = False
            self.numOfPOIs -=1
            if victim == "v":
                tile.numberOfVictims += 1


            # Se coloca otro poi en una posicion random
            x = self.random.randint(1, self.grid.width - 2)
            y = self.random.randint(1, self.grid.height - 2)
            tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]

        # Si el POI cae en otro poi...
        # se disminuye el numero de pois
        while tile.hasPOI == True:
            # Se coloca otro poi en una posicion random
            x = self.random.randint(1, self.grid.width - 2)
            y = self.random.randint(1, self.grid.height - 2)
            tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]

        print(f"Position of POI in {x, y}")
        self.POIsPositions.append(tile.pos)
        # Se coloca POI
        tile.hasPOI = True
        tile.poi = victim
        self.currentPOIS += 1
        # Apagar fuegos o smokes
        if tile.fireStatus != 0:
            tile.fireStatus  = 0

        if victim == "v":
            tile.numberOfVictims += 1
            self.truePOIs -= 1
        else:
            self.falsePOIs -= 1

        # Imprime datos relacionados con POI
        print("Has poi: ", tile.hasPOI)
        print("Number of victims: ", tile.numberOfVictims)
        print("POI type: ", tile.poi)
        self.appendAffectedTile(tile,"stand", 0, 0)
        print(f"Affected tiles:")
        for tilelist in self.affectedTiles:
            print(tilelist)
        self.affectedTiles = []


    def replenishPOIs(self):

      while self.currentPOIS < 3 and self.numOfPOIs > 0:
        print("Replenishing POIs")
        x = self.random.randint(1, self.grid.width - 2)
        y = self.random.randint(1, self.grid.height - 2)
        tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]

        numF = self.falsePOIs
        numV = self.truePOIs if self.truePOIs > 0 else 1
        chance = numF/numV

        # Escoge aleatoriamente entre 1 y 100
        random_number = self.random.randint(1, 100)

        if(chance > random_number/100):
          self.spawnPOI(x, y, tile, "f")
          numF -= 1
        else:
          self.spawnPOI(x, y, tile, "v")
          numV -= 1

      # Print the location of the tiles with .hasPOI
      self.POIsPositions = []
      for i in range(self.grid.width - 1): # iterate over grid width
        for j in range(self.grid.height - 1): # iterate over grid height
            for obj in self.grid.get_cell_list_contents([(i, j)]):
                if isinstance(obj, Tile) and obj.hasPOI:
                    print(f"Tile with .hasPOI at position: {obj.pos}")
                    self.POIsPositions.append(obj.pos)


    def step(self):
        self.affectedTiles = []
        print(f"Step: {self.steps} ===========================================================")
        self.dictionaryList.append(self.currentAgentsDictionary)
        self.currentAgentsDictionary = {}
        if self.savedVictims >= 7:
            self.win += 1
            print("Game over you won")
            self.running = False
            return
        elif self.damageCounter >= 24 or self.deadVictims >= 4 :
            self.lose += 1
            print("Game over you lost")
            self.running = False
            return
        else:
            self.datacollector.collect(self)
            self.schedule.step()
            self.steps += 1
            print(f"Damage counter: {self.damageCounter}")
            print(f"Dead victims: {self.deadVictims}")
            print(f"Saved victims: {self.savedVictims}")
            print(f"Current POIs: {self.currentPOIS}")


            # send data()

    def killFirefighter(self, tile):
        if len(tile.hasFireFighter) > 0:
            for firefighter in tile.hasFireFighter:
                print(f"Killing {firefighter.unique_id}")
                if firefighter.carrying == True:
                    print("Dead victim")
                    firefighter.carrying = False
                    self.deadVictims += 1
                # mueve al agente a la posicion inicial
                firefighter.move(firefighter.initialPos)


    def throwDice(self):
        x = self.random.randint(1, self.grid.width - 2)
        y = self.random.randint(1, self.grid.height - 2)

        print(f"Tile position: {x}, {y}")
        tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]
        if tile.fireStatus == 0:
            print(f"Spawn a smoke")
            tile.fireStatus = 1
            self.appendAffectedTile(tile,"stand", 0, 0)
            print(f"Affected tiles:")
            for tilelist in self.affectedTiles:
                print(tilelist)
            self.affectedTiles = []
            # Abajo
            if x + 1 <= self.grid.width - 2:
                bottom_tile = [obj for obj in self.grid.get_cell_list_contents([(x + 1, y)]) if isinstance(obj, Tile)][0]
                if bottom_tile.fireStatus == 2 and (tile.wall.bottom == 0 or (tile.wall.isDoor == 3 and tile.wall.isOpen)):
                    tile.fireStatus = 2
                    self.spreadFire(x, y)

             # Arriba
            if x - 1 >= 1:
                top_tile = [obj for obj in self.grid.get_cell_list_contents([(x - 1, y)]) if isinstance(obj, Tile)][0]
                if top_tile.fireStatus == 2 and (tile.wall.top == 0 or (tile.wall.isDoor == 1 and tile.wall.isOpen)):
                    tile.fireStatus = 2
                    self.spreadFire(x, y)

            # Izquierda
            if y - 1 >= 1:
                left_tile = [obj for obj in self.grid.get_cell_list_contents([(x, y - 1)]) if isinstance(obj, Tile)][0]
                if left_tile.fireStatus == 2 and (tile.wall.left == 0 or (tile.wall.isDoor == 2 and tile.wall.isOpen)):
                    tile.fireStatus = 2
                    self.spreadFire(x, y)

            # Derecha
            if y + 1 <= self.grid.height - 2:
                right_tile = [obj for obj in self.grid.get_cell_list_contents([(x, y + 1)]) if isinstance(obj, Tile)][0]
                if right_tile.fireStatus == 2 and (tile.wall.right == 0 or (tile.wall.isDoor == 4 and tile.wall.isOpen)):
                    tile.fireStatus = 2
                    self.spreadFire(x, y)

            # Si el tile ya tiene fuego y tiene un POI, lo revela y mata a la victima en caso de tener
            if tile.fireStatus == 2:
                self.revealPOI(tile)
                self.killFirefighter(tile)

        elif tile.fireStatus == 1:
            print(f"Spawn fire")
            tile.fireStatus = 2
            self.killFirefighter(tile)

            # Si el tile con fuego tiene un POI, lo revela y mata a la victima en caso de tener
            self.revealPOI(tile)
            self.spreadFire(x, y)
            # añadir funcion de propagar el fuego
        elif tile.fireStatus == 2:
            print("Explosion")
            self.makeExplosion(x, y)
            print(f"Affected tiles:")
            for tilelist in self.affectedTiles:
                print(tilelist)
            self.affectedTiles = []

    def moveDirection(self, x, y, dx, dy):
        # Verificar que la posición actual esté dentro de los límites del grid
        if x < 1 or y < 1 or x > self.grid.width-2 or y > self.grid.height-2:
            return

        # Obtener el tile actual
        current_tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]
        #print(f"Current position: {current_tile.pos}")
        #print(f"Wall properties: Top={current_tile.wall.top}, Bottom={current_tile.wall.bottom}, Left={current_tile.wall.left}, Right={current_tile.wall.right}")
        #print(f"Wall health properties: Top={current_tile.wall.topHealth}, Bottom={current_tile.wall.bottomHealth}, Left={current_tile.wall.leftHealth}, Right={current_tile.wall.rightHealth}")
        #print(f"Door: {current_tile.wall.isDoor}")

        # Verificar si hay humo en el tile actual
        if current_tile.fireStatus == 1 or current_tile.fireStatus == 0:
            current_tile.fireStatus = 2

            self.killFirefighter(current_tile)
            # Si el tile con fuego tiene un POI, lo revela y mata a la victima en caso de tener
            self.revealPOI(current_tile)

            #print(f"Fire placed at {x}, {y}. Stopping.")
            self.spreadFire(x, y)
            return

        # Verificar si hay una pared en la dirección en la que se quiere avanzar
        if (dx == -1 and (current_tile.wall.top != 0 or (current_tile.wall.isDoor == 1 and current_tile.wall.isOpen is False and current_tile.wall.topHealth > 0))) or \
         (dx == 1 and (current_tile.wall.bottom != 0 or (current_tile.wall.isDoor == 3 and current_tile.wall.isOpen is False and current_tile.wall.bottomHealth > 0))) or \
          (dy == -1 and (current_tile.wall.left != 0 or (current_tile.wall.isDoor == 2 and current_tile.wall.isOpen is False and current_tile.wall.leftHealth > 0))) or \
           (dy == 1 and (current_tile.wall.right != 0 or (current_tile.wall.isDoor == 4 and current_tile.wall.isOpen is False and current_tile.wall.rightHealth > 0))):

            if not ((current_tile.wall.top == 2 and dx == -1) or (current_tile.wall.left == 2 and dy == -1) or
              (current_tile.wall.bottom == 2 and dx == 1) or (current_tile.wall.right == 2 and dy == 1)):
                self.damageCounter += 1

            if dx == -1:
                if x != 1:
                    other_tile = [obj for obj in self.grid.get_cell_list_contents([(x+dx, y+dy)]) if isinstance(obj, Tile)][0]
                    #print(f"Bottom wall properties: Top={other_tile.wall.top}, Bottom={other_tile.wall.bottom}, Left={other_tile.wall.left}, Right={other_tile.wall.right}")
                    #print(f"Bottom wall health properties: Top={other_tile.wall.topHealth}, Bottom={other_tile.wall.bottomHealth}, Left={other_tile.wall.leftHealth}, Right={other_tile.wall.rightHealth}")
                    other_tile.wall.bottomHealth -= 2
                    if other_tile.wall.bottomHealth <= 0:
                        other_tile.wall.bottomHealth = 0
                        other_tile.wall.bottom = 0

                        if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                            self.graph[(x+dx, y+dy)][(x, y)] = 1
                    else:
                        if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                            self.graph[(x+dx, y+dy)][(x, y)] = 3
                        #print(f"Bottom wall from tile ({x+dx},{y+dy}) destroyed with new value {other_tile.wall.bottom}")
                    self.appendAffectedTile(other_tile,"stand", 0, 0)

                #print(f"Previous health: {current_tile.wall.topHealth}")

                current_tile.wall.topHealth -= 2
                if current_tile.wall.topHealth <= 0:
                    current_tile.wall.topHealth = 0
                    current_tile.wall.top = 0
                    #print("Top door destroyed")
                    self.spreadFire(x, y)

                    if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                        self.graph[(x, y)][(x+dx, y+dy)] = 1
                else:
                    if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                        self.graph[(x, y)][(x+dx, y+dy)] = 3
                self.appendAffectedTile(current_tile,"stand", 0, 0)

                    #print("Top wall damaged")

                #print(f"Top health: {current_tile.wall.topHealth}")
            elif dx == 1:
                if x != self.grid.width - 2:
                    other_tile = [obj for obj in self.grid.get_cell_list_contents([(x+dx, y+dy)]) if isinstance(obj, Tile)][0]
                    #print(f"Top wall properties: Top={other_tile.wall.top}, Bottom={other_tile.wall.bottom}, Left={other_tile.wall.left}, Right={other_tile.wall.right}")
                    #print(f"Top wall health properties: Top={other_tile.wall.topHealth}, Bottom={other_tile.wall.bottomHealth}, Left={other_tile.wall.leftHealth}, Right={other_tile.wall.rightHealth}")
                    other_tile.wall.topHealth -= 2
                    if other_tile.wall.topHealth <= 0:
                        other_tile.wall.topHealth = 0
                        other_tile.wall.top = 0
                        if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                            self.graph[(x+dx, y+dy)][(x, y)] = 1
                    else:
                        if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                            self.graph[(x+dx, y+dy)][(x, y)] = 3
                    self.appendAffectedTile(other_tile, "stand", 0, 0)
                        #print(f"Top wall from tile ({x+dx},{y+dy}) destroyed with new value {other_tile.wall.top}")



                #print(f"Previous health: {current_tile.wall.bottomHealth}")
                current_tile.wall.bottomHealth -= 2
                if current_tile.wall.bottomHealth <= 0:
                    current_tile.wall.bottomHealth = 0
                    current_tile.wall.bottom = 0
                    #print("Bottom door destroyed")
                    self.spreadFire(x, y)
                    if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                        self.graph[(x, y)][(x+dx, y+dy)] = 1
                else:
                    if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                        self.graph[(x, y)][(x+dx, y+dy)] = 3
                self.appendAffectedTile(current_tile,"stand", 0, 0)
                    #print("Bottom wall damaged")

                #print(f"Bottom health: {current_tile.wall.bottomHealth}")
            elif dy == -1:
                if y != 1:
                    other_tile = [obj for obj in self.grid.get_cell_list_contents([(x+dx, y+dy)]) if isinstance(obj, Tile)][0]
                    #print(f"Right wall properties: Top={other_tile.wall.top}, Bottom={other_tile.wall.bottom}, Left={other_tile.wall.left}, Right={other_tile.wall.right}")
                    #print(f"Right wall health properties: Top={other_tile.wall.topHealth}, Bottom={other_tile.wall.bottomHealth}, Left={other_tile.wall.leftHealth}, Right={other_tile.wall.rightHealth}")
                    other_tile.wall.rightHealth -= 2
                    if other_tile.wall.rightHealth <= 0:
                        other_tile.wall.rightHealth = 0
                        other_tile.wall.right = 0
                        if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                            self.graph[(x+dx, y+dy)][(x, y)] = 1
                    else:
                        if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                            self.graph[(x+dx, y+dy)][(x, y)] = 3
                    self.appendAffectedTile(other_tile,"stand", 0, 0)
                        #print(f"Right wall from tile ({x+dx},{y+dy}) destroyed with new value {other_tile.wall.right}")


                #print(f"Previous health: {current_tile.wall.leftHealth}")
                current_tile.wall.leftHealth -= 2
                if current_tile.wall.leftHealth <= 0:
                    current_tile.wall.leftHealth = 0
                    current_tile.wall.left = 0
                    self.spreadFire(x, y)
                    if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                        self.graph[(x, y)][(x+dx, y+dy)] = 1
                else:
                    if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                        self.graph[(x, y)][(x+dx, y+dy)] = 3
                self.appendAffectedTile(current_tile,"stand", 0, 0)
                    #print("Left wall damaged")

                #print(f"Left health: {current_tile.wall.leftHealth}")

            elif dy == 1:
                if y != self.grid.height - 2:
                    other_tile = [obj for obj in self.grid.get_cell_list_contents([(x+dx, y+dy)]) if isinstance(obj, Tile)][0]
                    #print(f"Left wall properties: Top={other_tile.wall.top}, Bottom={other_tile.wall.bottom}, Left={other_tile.wall.left}, Right={other_tile.wall.right}")
                    #print(f"Left wall health properties: Top={other_tile.wall.topHealth}, Bottom={other_tile.wall.bottomHealth}, Left={other_tile.wall.leftHealth}, Right={other_tile.wall.rightHealth}")
                    other_tile.wall.leftHealth -= 2
                    if other_tile.wall.leftHealth <= 0:
                        other_tile.wall.leftHealth = 0
                        other_tile.wall.left = 0

                        if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                            self.graph[(x+dx, y+dy)][(x, y)] = 1
                    else:
                        if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                            self.graph[(x+dx, y+dy)][(x, y)] = 3
                    self.appendAffectedTile(other_tile,"stand", 0, 0)
                        #print(f"Left wall from tile ({x+dx},{y+dy}) destroyed with new value {other_tile.wall.left}")



                #print(f"Previous health: {current_tile.wall.rightHealth}")
                current_tile.wall.rightHealth -= 2
                if current_tile.wall.rightHealth <= 0:
                    current_tile.wall.rightHealth = 0
                    current_tile.wall.right = 0
                    #print("Right door destroyed")
                    self.spreadFire(x, y)
                    if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                        self.graph[(x, y)][(x+dx, y+dy)] = 1
                else:
                    if (x+dx < 6 and x+dx > 0) and (y+dy > 0 and y+dy < 8):
                        self.graph[(x, y)][(x+dx, y+dy)] = 3
                self.appendAffectedTile(current_tile,"stand", 0, 0)

                    #print("Right wall damaged")

                #print(f"Right health: {current_tile.wall.rightHealth}")
            return

        # Moverse a la siguiente posición según la dirección dada
        new_x = x + dx
        new_y = y + dy

        # Llamada recursiva para continuar moviéndose en la dirección especificada
        self.moveDirection(new_x, new_y, dx, dy)

    def makeExplosion(self, x, y):
        current_tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]
        #print(f"Current position: {current_tile.pos}")

        # Abajo
        #print("Moving down")
        self.moveDirection(x, y, 1, 0)

        # Arriba
        #print("Moving up")
        self.moveDirection(x, y, -1, 0)

        # Izquierda
        #print("Moving left")
        self.moveDirection(x, y, 0, -1)

        # Derecha
        #print("Moving right")
        self.moveDirection(x, y, 0, 1)

    def spreadFire(self, x, y):
        # Obtener el tile en la posición (x, y)
        current_tile = [obj for obj in self.grid.get_cell_list_contents([(x, y)]) if isinstance(obj, Tile)][0]

        # Si el tile con fuego tiene un POI, lo revela y mata a la victima en caso de tener
        self.revealPOI(current_tile)
        self.appendAffectedTile(current_tile,"stand", 0, 0)
        print(f"Affected tiles:")
        for tilelist in self.affectedTiles:
            print(tilelist)
        self.affectedTiles = []
        #print(f"Current position: {current_tile.pos}")
        # Verificar si la propiedad fireStatus del tile actual no es 0
        if current_tile.fireStatus != 0:
            # Verificar y propagar el fuego a los tiles adyacentes

            # Abajo
            if x + 1 <= self.grid.width - 2:  # Asegurar que no se salga del límite
                bottom_tile = [obj for obj in self.grid.get_cell_list_contents([(x + 1, y)]) if isinstance(obj, Tile)][0]
                #print(f"Bottom tile: {bottom_tile.fireStatus}")
                #print(f"Bottom pos: {bottom_tile.pos}")
                if bottom_tile.fireStatus == 1 and (current_tile.wall.bottom == 0 or (current_tile.wall.isDoor == 3 and (current_tile.wall.isOpen or current_tile.wall.bottomHealth <= 0))):
                    bottom_tile.fireStatus = 2
                    #print("Spread down")
                    #print(f"Current tile: {bottom_tile.pos}")

                    # Llamar recursivamente para propagar el fuego desde el tile derecho
                    self.spreadFire(x + 1, y)

            # Arriba
            if x - 1 >= 1:  # Asegurar que no se salga del límite
                top_tile = [obj for obj in self.grid.get_cell_list_contents([(x - 1, y)]) if isinstance(obj, Tile)][0]
                #print(f"Top tile: {top_tile.fireStatus}")
                #print(f"Top pos: {top_tile.pos}")
                if top_tile.fireStatus == 1 and (current_tile.wall.top == 0 or (current_tile.wall.isDoor == 1 and (current_tile.wall.isOpen or current_tile.wall.topHealth <= 0))):
                    top_tile.fireStatus = 2
                    #print("Spread top")
                    #print(f"Current tile: {top_tile.pos}")
                    # Llamar recursivamente para propagar el fuego desde el tile izquierdo
                    self.spreadFire(x - 1, y)

            # Izquierda
            if y - 1 >= 1:  # Asegurar que no se salga del límite
                left_tile = [obj for obj in self.grid.get_cell_list_contents([(x, y - 1)]) if isinstance(obj, Tile)][0]
                #print(f"Left tile: {left_tile.fireStatus}")
                #print(f"Left pos: {left_tile.pos}")
                if left_tile.fireStatus == 1 and (current_tile.wall.left == 0 or (current_tile.wall.isDoor == 2 and (current_tile.wall.isOpen or current_tile.wall.leftHealth <= 0))):
                    left_tile.fireStatus = 2
                    #print("Spread left")
                    #print(f"Current tile: {left_tile.pos}")
                    # Llamar recursivamente para propagar el fuego desde el tile superior
                    self.spreadFire(x, y - 1)

            # Derecha
            if y + 1 <= self.grid.height - 2:  # Asegurar que no se salga del límite
                right_tile = [obj for obj in self.grid.get_cell_list_contents([(x, y + 1)]) if isinstance(obj, Tile)][0]
                #print(f"Right tile: {right_tile.fireStatus}")
                #print(f"Right pos: {right_tile.pos}")
                if right_tile.fireStatus == 1 and (current_tile.wall.right == 0 or (current_tile.wall.isDoor == 4 and (current_tile.wall.isOpen or current_tile.wall.rightHealth <= 0))):
                    right_tile.fireStatus = 2
                    #print("Spread right")
                    #print(f"Current tile: {right_tile.pos}")
                    # Llamar recursivamente para propagar el fuego desde el tile inferior
                    self.spreadFire(x, y + 1)

    def print_wall(self):
        for i in range(1, self.grid.width-1):
            for j in range(1, self.grid.height-1):
                tile = [obj for obj in self.grid.get_cell_list_contents([(i, j)]) if isinstance(obj, Tile)][0]
                print(f"Tile position: {tile.pos}")
                print(f"Health properties: Top={tile.wall.topHealth}, Bottom={tile.wall.bottomHealth}, Left={tile.wall.leftHealth}, Right={tile.wall.rightHealth}")
                print(f"Wall properties: Top={tile.wall.top}, Bottom={tile.wall.bottom}, Left={tile.wall.left}, Right={tile.wall.right}")
                print(f"Door properties: {tile.wall.isDoor}")
                print(f"Fire status: {tile.fireStatus}")
                print(f"Has POI: {tile.hasPOI}")
                print(f"Number of victims: {tile.numberOfVictims}")
                print(f"POI type: {tile.poi}")


    def generate_graph(self, matrix):
        rows = len(matrix)
        cols = len(matrix[0])
        graph = {}

        for x in range(1, rows + 1):  # 1-based index
            for y in range(1, cols + 1):
                node = (x, y)
                graph[node] = {}

                # Assign variables to each one of the 4 numbers
                WXYZ = matrix[x-1][y-1]  # Keep the original string
                W, X, Y, Z = int(WXYZ[0]), int(WXYZ[1]), int(WXYZ[2]), int(WXYZ[3])

                if W == 0 and x > 1:  # UP: Connect to (x-1, y)
                    graph[node][(x-1, y)] = 1
                elif W == 1 and x > 1:  # Wall UP: Connect with cost 5
                    graph[node][(x-1, y)] = 5

                if X == 0 and y > 1:  # LEFT: Connect to (x, y-1)
                    graph[node][(x, y-1)] = 1
                elif X == 1 and y > 1:  # Wall LEFT: Connect with cost 5
                    graph[node][(x, y-1)] = 5

                if Y == 0 and x < rows:  # DOWN: Connect to (x+1, y)
                    graph[node][(x+1, y)] = 1
                elif Y == 1 and x < rows:  # Wall DOWN: Connect with cost 5
                    graph[node][(x+1, y)] = 5

                if Z == 0 and y < cols:  # RIGHT: Connect to (x, y+1)
                    graph[node][(x, y+1)] = 1
                elif Z == 1 and y < cols:  # Wall RIGHT: Connect with cost 5
                    graph[node][(x, y+1)] = 5
        return graph

    def add_door_arches(self, graph, door_arches, cost):
        for arch in door_arches:
            x1, y1, x2, y2 = arch
            node1 = (x1, y1)
            node2 = (x2, y2)

            if node1 in graph:
                graph[node1][node2] = cost
            if node2 in graph:
                graph[node2][node1] = cost
        return graph

    def printMatrixTiles(self):
        # Imprime la matriz "tilesMatrix" con el valor que guarda
        for key in self.tilesMatrix:
            print(f"Pair {key}: {self.tilesMatrix[key]}")

    def createInitialDictionary(self):
        self.initialDictionary = {}
        for i in range(1, self.grid.width-1):
            for j in range(1, self.grid.height-1):
                tile = [obj for obj in self.grid.get_cell_list_contents([(i, j)]) if isinstance(obj, Tile)][0]
                firefightersIDs = []
                for firefighter in tile.hasFireFighter:
                    firefightersIDs.append(firefighter.unique_id)

                self.initialDictionary[(i, j)] = {"top": tile.wall.top,
                                                  "left": tile.wall.left,
                                                  "bottom": tile.wall.bottom,
                                                  "right": tile.wall.right,
                                                  "isOpen": tile.wall.isOpen,
                                                  "topHealth": tile.wall.topHealth,
                                                  "leftHealth": tile.wall.leftHealth,
                                                  "bottomHealth": tile.wall.bottomHealth,
                                                  "rightHealth": tile.wall.rightHealth,
                                                  "fireStatus": tile.fireStatus,
                                                  "hasPoi": tile.hasPOI,
                                                  "numberVictims": tile.numberOfVictims,
                                                  "firefighters": firefightersIDs}

WIDTH = 10
HEIGHT = 8
FIREFIGHTERS = 6
MAX_ITERATIONS = 50
iteration = 0

def process_file(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()

    walls = []
    POIS = []
    fires = []
    doors = []
    entryPoints = []

    for i in range(6):
        row = []
        binary = lines[i].strip().split()
        for num in binary:
            wall = [int(num[0]), int(num[1]), int(num[2]), int(num[3])]
            row.append(wall)
        walls.append(row)

    rest = [line.strip().split() for line in lines[6:]]

    for item in rest:
        if len(item) == 3 and item[2] in ['v', 'f']:
            POIS.append([int(item[0]), int(item[1]), item[2]])
        elif len(item) == 2:
            break

    for item in rest:
        if len(item) == 2:
            fires.append([int(item[0]), int(item[1])])
        elif len(item) == 4:
            break

    for item in rest:
        if len(item) == 4:
            doors.append([int(x) for x in item])
        elif len(item) == 2 and [int(item[0]), int(item[1])] not in fires:
            break

    for item in rest[::-1]:
        if len(item) == 2:
            entryPoints.append((int(item[0]), int(item[1])))
        else:
            break
    entryPoints.reverse()

    return walls, POIS, fires, doors, entryPoints

filename = "input.txt"
walls, POIS, fires, doors, entryPoints = process_file(filename)



#print(model.printMatrixTiles())
model = FireRescueModel(FIREFIGHTERS, HEIGHT, WIDTH, entryPoints, walls, doors, fires, POIS)

# imprime el diccionario inicial
model.createInitialDictionary()
for key in model.initialDictionary:
    print(f"{key}: {model.initialDictionary[key]}")

while model.running:
    model.step()

# imprime la lista de diccionarios
for i in range(1, len(model.dictionaryList)):
    print(f"Dictionary {i}:")
    for key in model.dictionaryList[i]:
        print(f"{key} {model.dictionaryList[i][key]}")

print(model.dictionaryList)
print("end")

def parse_actions(x):
    return {
        "x": x[0][0],
        "y": x[0][1],
        "top": x[1],
        "left": x[2],
        "bottom": x[3],
        "right": x[4],
        "isOpen": x[5],
        "topHealth": x[6],
        "leftHealth": x[7],
        "bottomHealth": x[8],
        "rightHealth": x[9],
        "fireStatus": x[10],
        "hasPOI": x[11],
        "numberOfVictims": x[12],
        "firefightersIDs": x[13],
        "actions": x[14],
        "dx": x[15],
        "dy": x[16],
        "damageCounter": x[17],
        "poi": x[18],
        "savedVictims": x[19],
        "deadVictims": x[20]
    }

pending_actions = {}

for (k, v) in enumerate(model.dictionaryList):

    n1_acc = []
    for xx, xy in v.items():
      n2_acc = []
      for yy, y in enumerate(xy):
        n2_acc.append({
            "model_step_id": yy,
            "affected_tiles_data": parse_actions(y)
        })

      n1 = {
          "bot_id": xx,
          "agent_step_data": n2_acc
      }
      n1_acc.append(n1)
    pending_actions[f"run_{k}"] = n1_acc

parsedJSON = json.dumps(pending_actions, indent=4)

print("===========================================================================================================")
print(parsedJSON)

# TC2008B Modelación de Sistemas Multiagentes con gráficas computacionales
# Python server to interact with Unity via POST
# Sergio Ruiz-Loza, Ph.D. March 2021

from http.server import BaseHTTPRequestHandler, HTTPServer
import logging
import json

class Server(BaseHTTPRequestHandler):
    request_count = 0

    def _set_response(self):
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()

    def do_GET(self):
        self._set_response()
        self.wfile.write("GET request for {}".format(self.path).encode('utf-8'))

    def do_POST(self):
        Server.request_count += 1
        logging.info(f"Recieved POST request #{Server.request_count}")
        tiles = model.initialDictionary
        tiles_serialized = {f"{k[0]},{k[1]}": v for k, v in tiles.items()}

        if Server.request_count == 1:
            self._set_response()
            self.wfile.write(json.dumps(tiles_serialized).encode('utf-8'))
            logging.info("Sent tiles")
        else:
            self._set_response()
            self.wfile.write(parsedJSON.encode('utf-8'))
            logging.info("Sent moves")
            Server.request_count = 0


def run(server_class=HTTPServer, handler_class=Server, port=8585):
    logging.basicConfig(level=logging.INFO)
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    logging.info("Starting httpd...\n") # HTTPD is HTTP Daemon!

    try:
        httpd.serve_forever()
    except KeyboardInterrupt:   # CTRL+C stops the server
        pass
    httpd.server_close()
    logging.info("Stopping httpd...\n")

if __name__ == '__main__':
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()

